### PR TITLE
built characters attributes

### PR DESCRIPTION
**Pull request by bflannery**
checkout my attributes and prototypes. if these work I will start on building "Select Character" screen

### CODE REVIEW

**Comment by misterussell** [comment]
Cool thanks! The constructor looks good so far.

**Comment by misterussell** [comment]
Let's change the name of the weapon .method on the Character prototype to attack so that it is more semantically in line with what we want the function to do. Maybe rather than .weapon, we do .attack?

**Comment by bflannery** [comment]
Added a Battle button to the page! Can't get the images to upload but will work on that tomorrow. Let me know what you guys think otherwise

**Comment by misterussell** [comment]
Looks good! We can look over the images today.

**Pull request merged**
